{% set version = "1.4.12" %}

package:
  name: fastavro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fastavro/fastavro-{{ version }}.tar.gz
  sha256: 28c0d63eb286e64e9da79e083e299c33f1df65a490a1d79444dc453950daca40

build:
  number: 0
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - pytz

test:
  requires:
    - nose
    - flake8
  imports:
    - fastavro

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  dev_url: https://github.com/fastavro/fastavro

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scottbelden
    - tebeka
