{% set version = "1.1.0" %}

package:
  name: fastavro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fastavro/fastavro-{{ version }}.tar.gz
  sha256: 9465fd4eb65f227a665e3e9485c5610c032c84d5284a08ffcace91c0ca9e5eca

build:
  number: 0
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - pytz

test:
  requires:
    - nose
    - flake8
  imports:
    - fastavro

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  dev_url: https://github.com/fastavro/fastavro

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - scottbelden
    - tebeka
